language: node_js
node_js:
  - '7'
  - '6'
env:
  - CXX=g++-4.8
services:
  - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - yarn lint
  - yarn test
