language: node_js
node_js:
  - '6'
env:
  - CXX=g++-4.8
services:
  - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run lint
  - npm run test
